name: 🚀 Publish new version 

on:
  push:
    tags:
        - "v*"  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install deps
      run: npm install
    - name: Run tests
      run: xvfb-run -a npm test
    - name: Build
      run: npm run vscode:prepublish
    - name: Publish to vs code marketplace
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
  